import "dotenv/config";
export const port = Number(process.env.PORT);
export const DbUrl = String(process.env.DB_URL);
export const AwsBucketName = String(process.env.AWS_BUCKET_NAME);
export const AwsRegion = String(process.env.AWS_REGION);
export const AwsAccessKey = String(process.env.AWS_ACCESS_KEY);
export const AwsSecretKey = String(process.env.AWS_SECRET_KEY);
export const CloudFrontUrl = String(process.env.CLOUD_FRONT_URL);
export const CloudFrontDistId = String(process.env.CLOUD_FRONT_DIST_ID);
export const AccessTokenSecret = String(process.env.ACCESS_TOKEN_SECRET);
export const RefreshTokenSecret = String(process.env.REFRESH_TOKEN_SECRET);
export const Email = String(process.env.MAIL);
export const Password = String(process.env.MAIL_PASSWORD);
export const Host = String(process.env.MAIL_HOST);
